.github/workflows/testing.yml
presentation/server/__init__.py

#7: downgrade python to 3.10

---

tests/integration/sources_test.py

#7: cleaned tests up a bit

---

.github/workflows/testing.yml
makefile

- moved pylint and mypy to 'extras' test suite

#7: removed pylint from general test suite

---

.gitignore
requirements.txt

#7
Замеченные во время написания документации ошибки и проблемы в зависимостях и установочных файлах.

#7: added common gitignore and updated requirements.txt

---

app/lib/testing/__init__.py
app/lib/testing/postgres.py
app/lib/testing/redis.py
tests/integration/download_vizier_table_test.py
tests/integration/queue_test.py
tests/integration/sources_test.py

#60: speed up integration tests

---

app/data/interface/common_repository.py
app/data/repositories/common_repository.py
app/data/template.py
app/domain/model/source.py
app/domain/usecases/__init__.py
app/presentation/server/handlers/create_source.py
app/presentation/server/handlers/get_source.py
app/presentation/server/handlers/get_source_list.py
tests/integration/sources_test.py

- added title filter
- source requests now contain bibcode, title, authors and year directly

#88: fixed parameters in create source request

---

app/data/interface/common_repository.py
app/data/model/__init__.py
app/data/model/layer0.py
app/data/model/task.py
app/data/repositories/common_repository.py
app/data/repositories/layer0_repository.py
app/data/repositories/layer1_repository.py
app/data/template.py
app/domain/tasks/common.py
app/domain/tasks/download_vizier_table.py
app/lib/queue/__init__.py
app/lib/queue/task_status.py
app/lib/storage/enums.py
app/lib/storage/postgres/postgres_storage.py
app/lib/testing/postgres.py
postgres/migrations/V001__common.sql
postgres/migrations/V005__meta.sql
postgres/migrations/V006__rawdata.sql
postgres/migrations/V102__redshift.sql
postgres/migrations/V103__geometry.sql
postgres/migrations/V104__photometry.sql

#83: a bunch of small fixes to the layer0 repo

---

app/presentation/server/handlers/create_source.py

added bib year validation

---

app/domain/usecases/__init__.py
app/lib/clients/__init__.py
app/presentation/commands/runserver/config.py
app/presentation/commands/runserver/start.py
tests/domain/search_catalogs_test.py
tests/integration/download_vizier_table_test.py
tests/integration/queue_test.py
tests/integration/rawdata_table_test.py
tests/integration/sources_test.py

#87: moved clients to separate struct

---

app/commands/runserver/config.py
pyproject.toml
tests/integration/download_vizier_table_test.py

#7: fix numpy 2.0 release

---

app/presentation/server/handlers/create_source.py
app/presentation/server/handlers/create_table.py

#7: fix schema in server

---

app/domain/actions/create_table.py
tests/domain/create_table_test.py

#173: added units validation to POST /table method

---

app/data/repositories/common_repository.py
app/data/repositories/layer0_repository.py
app/domain/actions/create_table.py
app/domain/actions/login.py
app/domain/actions/start_task.py
app/lib/exceptions/__init__.py
app/lib/server/middleware.py
app/lib/storage/postgres/postgres_storage.py
app/presentation/server/handlers/add_data.py
app/presentation/server/handlers/create_source.py
app/presentation/server/handlers/create_table.py
app/presentation/server/handlers/get_source.py
app/presentation/server/handlers/get_task_info.py
app/presentation/server/handlers/login.py
app/presentation/server/handlers/start_task.py
tests/domain/create_table_test.py
tests/integration/rawdata_table_test.py

#158: made api errors subclasses instead of instances

---

app/data/interface/common_repository.py
app/data/mappers/data_to_domain.py
app/data/model/common.py
app/data/repositories/common_repository.py
app/data/repositories/layer_0_repository_impl.py
app/data/template.py
app/domain/actions/get_source.py
app/domain/model/source.py
app/domain/tasks/download_vizier_table.py
postgres/migrations/V001__common.sql
postgres/migrations/V002__designation.sql

#175: rename bibcode field to code

---

.github/workflows/app-deploy.yaml

#168: release workflow

---

app/domain/actions/create_table.py
app/domain/model/table.py
app/presentation/server/handlers/create_table.py
tests/domain/create_table_test.py
tests/integration/rawdata_table_test.py

#187: added ucd support to create_table action and API method

---

app/presentation/server/handlers/create_table.py
infra/makefile

#187: fix infra scripts and ucd and unit defaults

---

app/lib/storage/mapping.py

я забыла что надо вручную тыкать пр

extended type_map

---

app/presentation/server/handlers/create_source.py
app/presentation/server/handlers/create_table.py

#187: fix allow_none param in schemas

---

app/domain/actions/create_table.py
app/domain/actions/table_process.py
app/domain/converters/__init__.py
app/domain/converters/composite.py
app/lib/web/errors/__init__.py
tests/domain/table_process_test.py

#194: added composite converter, web.error docstrings and logical web error

---

app/commands/__init__.py
app/commands/depot.py
app/data/repositories/common_repository.py
app/data/repositories/layer0_repository.py
app/domain/actions/__init__.py
app/domain/actions/set_table_status.py
app/domain/actions/table_process.py
app/entities/object.py
app/lib/testing/__init__.py
app/lib/testing/mocks.py
app/presentation/server/handlers/__init__.py
app/presentation/server/handlers/set_table_status.py
app/schema/table_status.py
postgres/migrations/V001__common.sql
postgres/migrations/V006__rawdata.sql
tests/data/layer0_repository_test.py
tests/domain/add_data_test.py
tests/domain/create_table_test.py
tests/domain/set_table_status_test.py
tests/domain/table_process_test.py
tests/integration/download_vizier_table_test.py
tests/integration/rawdata_table_test.py
tests/lib/auth_test.py

#206: added some logic to set table status handler, added test helpers

---

app/data/repositories/layer0_repository.py
app/domain/actions/set_table_status.py
app/domain/actions/table_process.py
app/entities/object.py
postgres/migrations/V006__rawdata.sql
tests/domain/set_table_status_test.py

#206: added parsed object data info to rawdata.objects table

---

.github/workflows/documentation-deploy.yml
.github/workflows/regression-testing.yml
.github/workflows/testing.yml
app/domain/actions/create_table.py
app/lib/testing/__init__.py
app/lib/testing/common.py
app/lib/testing/decorators.py
app/lib/testing/postgres.py
app/lib/testing/redis.py
app/lib/testing/web.py
app/schema/table.py
main.py
makefile
tests/regression/upload_simple_table.py

#206: added regression test for uploading table

---

app/data/model/layer1.py
app/data/repositories/layer1_repository.py
app/domain/actions/set_table_status.py
app/domain/serializers/__init__.py
app/domain/serializers/composite.py
app/domain/serializers/designation.py
app/domain/serializers/interface.py
postgres/migrations/V102__designation.sql

#206: added name serializer

---

app/lib/web/server/__init__.py
app/lib/web/server/routes.py
app/presentation/server/handlers/add_data.py
app/presentation/server/handlers/common.py
app/presentation/server/handlers/create_source.py
app/presentation/server/handlers/create_table.py
app/presentation/server/handlers/get_source.py
app/presentation/server/handlers/get_task_info.py
app/presentation/server/handlers/login.py
app/presentation/server/handlers/ping.py
app/presentation/server/handlers/set_table_status.py
app/presentation/server/handlers/start_task.py
app/presentation/server/handlers/table_process.py
app/presentation/server/handlers/table_status_stats.py

#214: move common route params to lib

---

app/commands/importer/__init__.py
app/commands/importer/command.py
app/data/model/common.py
app/data/repositories/layer1_repository.py
app/data/repositories/layer2_repository.py
configs/dev/importer.yaml
main.py
makefile
postgres/migrations/V202__layer2.sql

#214: implement importer command

---

app/domain/adminapi/actions.py
app/domain/adminapi/table_upload.py
app/presentation/adminapi/__init__.py
app/presentation/adminapi/add_data.py
app/presentation/adminapi/create_source.py
app/presentation/adminapi/create_table.py
app/presentation/adminapi/get_api_v1_table_validation.py
app/presentation/adminapi/get_task_info.py
app/presentation/adminapi/interface.py
app/presentation/adminapi/server.py
app/presentation/adminapi/set_table_status.py
app/presentation/adminapi/table_process.py
app/presentation/adminapi/table_status_stats.py
tests/unit/domain/table_validation_test.py

#231: added table validation method & remove admin tag from spec

---

app/data/template.py
app/domain/adminapi/table_upload.py

#231: support columns with different capitalisation

---

app/commands/adminapi/command.py
app/commands/dataapi/__init__.py
app/commands/dataapi/command.py
app/commands/generate_spec/command.py
app/commands/importer/command.py
app/commands/processor/__init__.py
app/commands/processor/command.py
app/commands/processor/config.py
app/lib/commands/interface.py
configs/dev/processor.yaml
main.py

#245: added empty table processing command & moved command help to class docstring

---

app/data/repositories/layer2_repository/repository.py
app/domain/dataapi/actions.py
tests/integration/layer2_repository_test.py

#245: added batch query method to layer 2 repository

---

app/data/repositories/layer2_repository/__init__.py
app/data/repositories/layer2_repository/filters.py
app/data/repositories/layer2_repository/repository.py
app/domain/dataapi/actions.py
app/presentation/dataapi/interface.py
app/presentation/dataapi/query_simple.py

#245: added designation close & redshift & pgc filters to layer 2 repository

---

app/data/model/__init__.py
app/data/model/designation.py
app/data/model/icrs.py
app/data/model/interface.py
app/data/model/layer0.py
app/data/model/redshift.py
app/data/repositories/layer0_repository.py
app/data/repositories/layer1_repository.py
app/data/repositories/layer2_repository/repository.py
app/domain/adminapi/table_transfer.py
app/domain/usecases/cross_identification.py
app/domain/usecases/transformation_0_1_use_case.py
app/lib/auth/interface.py
tests/integration/layer1_repository_test.py
tests/unit/domain/set_table_status_test.py
tests/unit/domain/transform_01.py
tests/unit/domain/util.py

#245: slight refactoring of catalog objects ahead of cross identification

---

app/data/repositories/layer2_repository/__init__.py
app/data/repositories/layer2_repository/filters.py
app/data/repositories/layer2_repository/repository.py
app/domain/adminapi/table_transfer.py
app/domain/dataapi/actions.py
tests/integration/layer2_repository_test.py

#245: added AND filter to layer2

---

app/data/model/__init__.py
app/data/model/layer2.py
app/data/repositories/layer2_repository/repository.py
app/domain/dataapi/actions.py
tests/integration/layer2_repository_test.py

#245: (int, list[catalog_object]) -> Layer2Object

---

app/commands/layer1_importer/__init__.py
app/commands/layer1_importer/command.py
app/commands/layer1_importer/config.py
app/commands/processor/command.py
app/data/model/__init__.py
app/data/model/layer0.py
app/data/repositories/layer0/objects.py
app/data/repositories/layer0/repository.py
app/data/repositories/layer1.py
app/domain/converters/redshift.py
main.py
postgres/migrations/V004__layer1_icrs.sql
postgres/migrations/V005__layer1_designation.sql
postgres/migrations/V006__layer1_redshift.sql
tests/integration/layer1_repository_test.py

#245: added layer1_importer command

---

app/commands/importer/command.py
app/commands/layer1_importer/command.py
app/data/model/__init__.py
app/data/model/designation.py
app/data/model/icrs.py
app/data/model/interface.py
app/data/model/layer1.py
app/data/model/redshift.py
app/data/repositories/common.py
app/data/repositories/layer0/objects.py
app/data/repositories/layer0/repository.py
app/data/repositories/layer1.py
postgres/migrations/V002__common.sql
postgres/migrations/V003__layer0.sql
postgres/migrations/V004__layer1_icrs.sql
postgres/migrations/V005__layer1_designation.sql
postgres/migrations/V006__layer1_redshift.sql
postgres/migrations/V007__layer2.sql
tests/integration/layer1_repository_test.py
tests/lib/postgres.py

#261: move all pgc-object_id connection to rawdata.pgc

---

infra/makefile

#272: fix make target

---

app/data/repositories/layer2/repository.py

#276: make layer 2 INSERTs batched

---

app/lib/web/server/middleware.py
app/lib/web/server/server.py
infra/scripts.py

#272: added CORS middleware & fixed deploy script slightly

---

app/data/repositories/layer0/repository.py
app/data/repositories/layer0/tables.py
app/domain/adminapi/table_upload.py
app/presentation/adminapi/interface.py
app/presentation/adminapi/patch_api_v1_table.py
tests/integration/adminapi_server_test.py
tests/integration/create_table_test.py
tests/integration/dataapi_server_test.py
tests/integration/processing_test.py
tests/lib/postgres.py
tests/lib/redis.py
tests/regression/upload_vizier_table.py

#284: use table_name in patch_table method

---

infra/deployment.py

#288: security stuff

---

app/data/model/icrs.py
app/data/model/layer2.py
app/data/model/redshift.py
app/data/repositories/layer2/repository.py
app/domain/dataapi/actions.py
app/domain/dataapi/parameterized_query.py
app/domain/responders/__init__.py
app/domain/responders/structured_responder.py
app/lib/web/server/routes.py
app/presentation/dataapi/__init__.py
app/presentation/dataapi/interface.py
app/presentation/dataapi/model.py
app/presentation/dataapi/query_simple.py

#316: sophisticated data schema

---

app/commands/adminapi/command.py
app/commands/dataapi/command.py
app/data/model/icrs.py
app/data/repositories/tmp_data.py
app/domain/cross_id_simultaneous_data_provider.py
app/domain/dataapi/actions.py
app/domain/dataapi/parameterized_query.py
app/domain/model/layer0/coordinates/icrs_descr.py
app/domain/responders/__init__.py
app/domain/responders/structured_responder.py
app/domain/usecases/cross_identification.py
app/lib/astronomy/__init__.py
app/lib/config/__init__.py
app/lib/web/middlewares/exception.py
app/presentation/dataapi/interface.py
configs/dev/dataapi.yaml
configs/prod/dataapi.yaml
configs/test/dataapi.yaml
pyproject.toml
tests/integration/processing_test.py
tests/unit/domain/parse_coords_test.py
tests/unit/domain/value_descr_test.py
tests/unit/lib/astronomy_test.py

#311: add apexes to velocity catalog

---

app/commands/runtask/command.py
app/data/model/__init__.py
app/data/model/interface.py
app/data/repositories/layer0/objects.py
app/data/repositories/layer0/repository.py
app/data/repositories/layer2/filters.py
app/data/repositories/layer2/params.py
app/data/repositories/layer2/repository.py
app/domain/homogenization/apply.py
app/domain/model/constants.py
app/lib/web/errors/__init__.py
app/tasks/crossmatch.py
app/tasks/layer1_import.py
app/tasks/layer2_import.py
app/tasks/process.py
app/tasks/registry.py
configs/dev/dataapi.yaml
plugins/matchers/circle_matcher.py
tests/integration/layer2_import_test.py
tests/integration/processing_test.py
tests/regression/upload_simple_table.py
tests/regression/upload_vizier_table.py
tests/unit/domain/selector_factory_test.py

#323: implement new crossmatch command

---

app/data/model/layer0.py
app/data/repositories/layer0/objects.py
app/data/repositories/layer0/repository.py
app/domain/adminapi/__init__.py
app/domain/adminapi/actions.py
app/domain/adminapi/crossmatch.py
app/lib/storage/enums.py
app/lib/storage/postgres/postgres_storage.py
app/presentation/adminapi/interface.py
app/presentation/adminapi/server.py
pyproject.toml
tests/lib/web.py
tests/regression/upload_simple_table.py

#333: implement crossmatch results list handler

---

app/domain/adminapi/table_upload.py
app/lib/concurrency/__init__.py
app/lib/concurrency/errorgroup.py
tests/lib/__init__.py
tests/lib/astronomy.py
tests/regression/upload_simple_table.py
tests/unit/lib/concurrency_test.py

#338: insert empty objects in add_data method & errgroup library method

---

app/data/repositories/layer1.py
app/domain/adminapi/actions.py
app/domain/adminapi/crossmatch.py
plugins/loader.py
tests/regression/upload_simple_table.py

#338: crossmatch result methods do not use data field of objects table

---

app/data/model/__init__.py
app/data/model/layer1.py
app/data/repositories/layer1.py
app/domain/adminapi/crossmatch.py
app/domain/unification/crossmatch/ci_types.py
app/tasks/crossmatch.py
tests.py
tests/lib/astronomy.py
tests/lib/colors.py
tests/lib/decorators.py
tests/regression/upload_simple_table.py

#338: use layer 1 marking in crossmatch task

---

app/data/repositories/layer0/objects.py
app/lib/web/middlewares/exception.py
postgres/migrations/V011__remove_rawdata_objects_columns.sql
tests/lib/decorators.py

#338: remove `data` field from `rawdata.objects`
